

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Game/Maps/M_HexTest.M_HexTest


EditorStartupMap=/Game/Game/Maps/M_HexTest.M_HexTest
GlobalDefaultGameMode=/Game/Game/BP/Core/BP_ClockworkGameMode.BP_ClockworkGameMode_C

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/ClockworkTactics")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/ClockworkTactics")
+ActiveClassRedirects=(OldClassName="TP_BlankGameModeBase",NewClassName="ClockworkTacticsGameModeBase")

[Core.Log]

;Engine
LogTemp=Log
LogWorld=Warning

;Game
LogHex=Verbose
LogClockwork=Verbose

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=160377744787A8B60162D290691BFBA8
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/Engine.RendererSettings]
r.ReflectionMethod=1
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1

